### ISSUE TITLE
Username override

### ISSUE THREAD

**Issue by ejiek** [ayushnix/tessen#1]
Right now tessen assumes that username should be taken from a filename.
And that's it.
It's fine but should not be the only option.

It would be nice to use `user` or `username` key to override a filename.
Since it's explicitly specified, a user should be quite certain, that it should be used over a filename.

**Comment by ayushnix** [comment]
> It would be nice to use `user` or `username` key to override a filename.

This should already be the case. If a `user: your-username` is present inside a file, it should show up in the menu. It shouldn't be `username: your-username` though, because tessen assumes `username` from the file.

**Comment by ejiek** [comment]
Exactly my point.
They are treated like different entities and only one of them is used for the autotype.

Better behaviour is to look for a user key in a file first.
Fallback to a filename only when it's not found.

**Comment by ayushnix** [comment]
> Better behaviour is to look for a user key in a file first.

Ah, understood.

So you want autotype to use the username from the file if the `user` or `username` key is present inside of it instead of assuming username as the file name, right?

Hmm, makes sense. I'll probably add this functionality since rofi-pass behaves the same way and some people would've chosen to write their usernames inside the file rather than in the filename itself.

Thanks for reporting this.

**Comment by ayushnix** [comment]
I've added a feature to use custom username key and prefer that instead of the filename if it's present. If a username key isn't present, `tessen` should fallback to using the basename of the selected file.

Please read the README or the man page for more details. Let me know if anything doesn't work as expected.
