### ISSUE TITLE
Add support for gopass

### ISSUE THREAD

**Issue by svrana** [ayushnix/tessen#14]
[gopass](https://github.com/gopasspw/gopass) is a rewrite of the venerable pass code in golang.  Unfortunately the commands are not always the same; the largest difference is gopass requires the use of a 'show' command to display output. Haven't tested the otp support, but with minimal changes tessen works really well with gopass.

**Comment by ayushnix** [comment]
I'd love to support gopass as well but I don't think I can add the ability to parse YAML files using bash in `tessen`. I guess I can use tools like [yq](https://github.com/mikefarah/yq) for that but I'm not sure if I should go down that route.

Since I don't use gopass myself, can you confirm if gopass uses [this](https://github.com/gopasspw/password-store-example/blob/master/secrets/kv.txt) key-value format like pass does or does it use/support [this](https://github.com/gopasspw/password-store-example/blob/master/secrets/yaml.txt) kind of YAML format as well?

If a gopass users uses the same format mentioned [here](https://www.passwordstore.org/#organization), adding support for gopass should be fairly trivial.

**Comment by svrana** [comment]
Yeah, same format. Just changing the invocation to gopass and using `gopass show` is working for me well enough to use.

**Comment by ayushnix** [comment]
Looks like gopass supports parsing YAML natively and also handles OTP. In addition, it also supports something they call "mounts" which is just multiple different password store dirs. There are other features and some subtle differences as well.

I'll work on adding gopass support properly but that might take some time. The PR #16 in its present form needs a bit more work to make sure it works as expected for all users. One of the initial issues I've come across is `gopass mounts`. `tessen` will need to scan all possible `.gpg` files in all active mounts.

**Comment by ayushnix** [comment]
@svrana A new version of tessen has been released and it supports parsing data from gopass. Let me know if there are any issues with it and I'll re-open this issue.
