### ISSUE TITLE
using tessen in guix / rde

### ISSUE THREAD

**Issue by qzdl** [ayushnix/tessen#17]
Hi, thanks for a nice program. 

I am using this in gnu guix, which has a strong emphasis on repeatability and transparency -- as such, would you be open to allowing the specification of binary paths for the menus, as opposed to reading them from PATH?

A discussion about the nature of the use is open here https://lists.sr.ht/~abcdw/rde-devel/patches/29583

Cheers! 
  Samuel

**Comment by ayushnix** [comment]
> would you be open to allowing the specification of binary paths for the menus, as opposed to reading them from PATH?

Sorry, I didn't get this. Could you elaborate? What are the changes that you're proposing?

> A discussion about the nature of the use is open here https://lists.sr.ht/~abcdw/rde-devel/patches/29583

I'm not familiar with guix but from I could see on that link, you're assuming that `tessen` will accept arbitrary configuration options for arbitrary dmenu programs. However, as I've mentioned [here](https://github.com/ayushnix/tessen/pull/13#issuecomment-1029347295), the feature to pass arbitrary dmenu backends and arguments will be removed in the next release of tessen, which should be out in the next few days.

So if you want to use `bemenu` with `tessen`, `tessen` will look for the `bemenu` binary and if `$BEMENU_OPTS` is set, it'll use that otherwise use a predefined set of options. This will be similar to how `tessen` behaved in v1.2.3.

**Comment by ayushnix** [comment]
I'm closing this because I haven't received any response. I've also observed that tessen has been packaged for guix for quite a while now and I haven't received any reports of issues on guix so far. Let me know if there are still any issues about this.
