### ISSUE TITLE
Custom autotype

### ISSUE THREAD

**Issue by ejiek** [ayushnix/tessen#2]
Right now `autotype` field is treated like a regular key value pair.

It would be nice to use it as an instruction for an autotype and hide it from selection.

**Comment by ayushnix** [comment]
> It would be nice to use it as an instruction for an autotype and hide it from selection.

I didn't understand this. Do you want to automatically autotype and not have to select it? You can do `tessen -a autotype` for that.

**Comment by ejiek** [comment]
Credit card is a good example of a custom autotype.
You don't need neither username nor password.

It can be something like

`:number :holder :exp :cvv`

**Comment by ayushnix** [comment]
Ah, so you want to hide the autotype option from the menu if the selected file doesn't really have a username or a password, like a file that stores credit card details, right?

Hmm, how can we distinguish such files from the usual files which do have a username and a password? Because that is usually what's expected. I also don't think it makes sense to let the user hide the auto-type option because it wouldn't be used for most of the password store entries.

**Comment by ayushnix** [comment]
Never mind, I guess you meant auto-typing custom key-value pairs rather the default selection of username and password, like rofi-pass does.

Hmm, I'll think about this.

**Comment by ejiek** [comment]
Right now there is an option 'Autotype username and password'.

I suggest to turn it into 'Autotype' and make it configurable.

I've seen implementation of this through autotype key.
It means that we have to treat this key as a special case.

**Comment by ayushnix** [comment]
I've added a feature to use custom autotype. Please read the README or the man page. Let me know if everything works fine.
