### ISSUE TITLE
Support to ignore upper and lower case when searching

### ISSUE THREAD

**Issue by d-vb** [ayushnix/tessen#28]
Since the search for entries is case sensitive, it is often difficult to find the appropriate entry. Is there perhaps already a configuration option that I have missed? Thank you very much.

**Comment by ayushnix** [comment]
I think case sensitivity depends on the dmenu program you're using.

**Comment by d-vb** [comment]
I have set a pull request https://github.com/ayushnix/tessen/pull/29 to solve the problem. I hope this is okay.

**Comment by ayushnix** [comment]
The PR seems fine but what if some users don't prefer case insensitive search when they use rofi with tessen?

This is the reason why I strongly prefer dmenu programs which support file based configurations. In fact, I will make [fuzzel](https://codeberg.org/dnkl/fuzzel) the default dmenu program for tessen as soon as a new version of fuzzel is released because it [recently merged support for file based configuration](https://codeberg.org/dnkl/fuzzel/pulls/122). It's also a "proper" wayland native application, unlike the [rofi-lbonn-wayland](https://github.com/lbonn/rofi) fork.

In this case, even though rofi supports file based configuration, it seems to have omitted configuration for case sensitivity in the dmenu mode even though an issue for it has been open for more than 3 years now.

**Comment by d-vb** [comment]
> This is the reason why I strongly prefer dmenu programs which support file based configurations. In fact, I will make [fuzzel](https://codeberg.org/dnkl/fuzzel) the default dmenu program for tessen as soon as a new version of fuzzel is released because it [recently merged support for file based configuration](https://codeberg.org/dnkl/fuzzel/pulls/122). It's also a "proper" wayland native application, unlike the [rofi-lbonn-wayland](https://github.com/lbonn/rofi) fork.

Okay. I just switched to `fuzzel` and have no more problems. Should have done it from the beginning. Thank you for your patience and explanation.

> The PR seems fine but what if some users don't prefer case insensitive search when they use rofi with tessen?

In the backend bemenu, however, an ignore-case was also built in. Since I no longer have a need for it, I'll leave the decision to you. :smile: 

> In this case, even though rofi supports file based configuration, it seems to have omitted configuration for case sensitivity in the dmenu mode even though an issue for it has been open for more than 3 years now.

Yes, that is a pity.

**Comment by ayushnix** [comment]
> Okay. I just switched to `fuzzel` and have no more problems. Should have done it from the beginning. Thank you for your patience and explanation.

That's good to know. After a new version of `fuzzel` is released, we'll be able to configure fuzzel using a config file and that should make things much better.

> In the backend bemenu, however, an ignore-case was also built in. Since I no longer have a need for it, I'll leave the decision to you. :smile:

Yeah, 😅, if you haven't noticed, I have [expressed disdain at bemenu](https://github.com/ayushnix/tessen/issues/5) for its lack of file based configuration several times before. The good news is that users can overwrite all the default options of bemenu if they want using the `BEMENU_OPTS` environment variable so if someone doesn't like case insensitivity, they can turn it off. The bad news is that environment variables suck for this use case as I've explained [here](https://codeberg.org/dnkl/fuzzel/issues/3#issuecomment-368703).

But it's a good thing you brought up this issue. I'll probably remove all the default options I've set for bemenu except `-l 10` and `-n` to provide the absolute minimal sane defaults. In addition to this, I'll probably discourage using bemenu in combination with tessen, although I won't remove support for bemenu.

Anyways, thanks for raising this issue.
