### ISSUE TITLE
select password by default

### ISSUE THREAD

**Issue by sambaccessnow** [ayushnix/tessen#32]
Hi, 
I'm looking for a way to select automatically the password once selected in tessen and skip the user/password selection as below

![Screenshot from 2022-10-12 15-27-46](https://user-images.githubusercontent.com/87818106/195355324-08f2ed71-a892-47c4-8633-e48f7be49345.png)

Is there a way to automatically select the password in tessen ?

**Comment by ayushnix** [comment]
This feature request is similar to another issue that has asked for [keyboard shortcuts](https://github.com/ayushnix/tessen/issues/30) to select keys and perform actions.

I'm waiting for the [next major release](https://codeberg.org/dnkl/fuzzel/issues/165) of fuzzel which will introduce file based configuration and custom keybindings. Once that's released, I'll start working custom keybindings which will allow you to select the password using a keyboard shortcut.

**Comment by so-rose** [comment]
I'm looking for the same! Is there any way to set a CLI or environment variable that bypasses this menu entirely, letting one pre-select ex. "password"?

**Comment by ayushnix** [comment]
@so-rose I don't think adding a CLI flag or an environment variable to select a specific key makes sense. If a user doesn't want to automatically select a password in some cases, launching `tessen` without that flag/env var doesn't sound like a good workflow.

The intended solution to this issue is using keyboard shortcuts with dmenu programs like fuzzel. Once keyboard shortcuts are implemented in fuzzel, we can assign a shortcut to automatically type/copy a username, password, and possibly other keys like URLs, OTPs.

**Comment by ayushnix** [comment]
I'm closing this ticket in favor of #30 since both of them have requested the same feature. Please leave your comments, if any, on that ticket.
